version: '3.9'
services:
  identity-database:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${MSSQL_PORT}:1433"
    env_file:
      - .env
    volumes:
      - ./data:/var/opt/sqlserver/data